"""Append one outcome and preserve evidence from the bounded correction experiment."""
import json,time,datetime,math
from pathlib import Path
import recording
cur=json.load(open('tools/current_mug_episode.json'));eid=cur['episode'];now=time.time()
note='Unsuccessful: bounded local fingertip correction reduced estimated top-image error 107 to 83 px. Staged descent and gentle closure at measured FK (.288858,.043761,.037204) reached empty aperture1.417, load96, goal0. Reopened; final ~16mm commanded depth adjustment reached measured (.285401,.043981,.018123), tilted/displaced mug; no further closure or lift. Retracted and returned home.'
r=recording.stop_recording(success=False,notes=note);print(r);Path('tools/last_mug_stop.json').write_text(json.dumps(r,indent=2))
obs=[]
for p in sorted(Path('tools/mug_observations').glob('*.json')):
 if p.stem.isdigit() and int(p.stem)/1e9>=cur['started']:
  obs.append(dict(time=int(p.stem)/1e9,state=str(p),top=str(p.with_name(p.stem+'_top.jpg')),wrist=str(p.with_name(p.stem+'_wrist.jpg'))))
correction=dict(episode_id=eid,hypothesis='Fingertip response measured against static background remains usable despite mug rocking; bounded correction then refreshed contact approach.',prior_jacobian_px_per_degree=[[-10.78,-1.31],[-.60,8.75]],command_delta_deg={'shoulder_pan':-2,'shoulder_lift':3,'wrist_flex':-3},before={'state':'tools/mug_observations/1790196220816854406.json','fixed_tip_px':[614,285],'target_px':[642,388],'error_norm_px':math.hypot(28,103)},after={'state':'tools/mug_observations/1790196239970503598.json','fixed_tip_px':[635,310],'target_px':[650,392],'error_norm_px':math.hypot(15,82)},pixel_uncertainty=6,target_motion_uncertainty_px=23,interpretation='Observed fixed-tip motion (+21,+25) px approximately agrees with bounded model (+17.6,+27.5). Relative image error improved but target rocking and depth prevent a verified grasp.',stability_check='tools/precontact_1790196294906242866/measurements.json',stability_caveat='Wrist dark-region centroid varied ~16 px across six frames and includes jaw occlusion; no stable-target claim.',operator_evidence='Independent 12-frame silhouette analysis supports real back-and-forth mug pose change, possibly rocking/settling. Cause unknown; no permanent offset applied.',next='Preserve measured pitch and explicitly align fixed jaw with handle opening at contact depth; image-plane error alone does not establish depth. Compare final geometry to verified side-handle baseline before another retention test.')
epath=Path('tools/bounded_correction_'+eid+'.json');epath.write_text(json.dumps(correction,indent=2))
p=Path('tools/mug_episode_ledger.json');ledger=json.loads(p.read_text())
if not any(e['id']==eid for e in ledger):ledger.append(dict(id=eid,started=cur['started'],finished=now,success=False,notes=note,observations=obs,experiment_ledger=str(epath),grasp_location_m=[.288858275,.043761455,.037204162],grasp_location_frame='base_link measured FK at unsuccessful closure, not mug base location',last_approach_fk_m=[.285400513,.043980748,.018123353],table_contact_location={'status':'Uncertain pre-contact body-support estimate; no coverage credit','precontact_body_support_pixel_estimate':[585,375],'uncertainty_m':.03,'calibration':'calibration/20260918T214001_327909148/workspace_map.json','method':'Approximate underside/body footprint, not handle projection. Rocking and occlusion preclude assigning a verified grid cell.'}))
p.write_text(json.dumps(ledger,indent=2))
s=json.load(open('tools/supervisor_status.json'));s.update(updated_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),successes=sum(e['success'] for e in ledger),unsuccessful_episodes=sum(not e['success'] for e in ledger),verified_successes_trailing_hour=sum(e['success'] and e.get('finished',0)>=now-3600 for e in ledger),latest_episode_id=eid,latest_result=note,experiment_ledger=str(epath),blocker='Projected fixed-jaw alignment did not produce opposing contact: empty closure at z .0372, displacement on deeper step to z .0181.',transferable_discovery=correction['interpretation'],next_hypothesis=correction['next'],turn_boundary='Recorder stopped, arm at saved four-joint home, gripper open, mug on table, torque retained.',history_reconciliation='All five prior current-assignment episodes retained by episode_id; appended current unsuccessful episode. Uploaded historical failure remains included.')
s['success_to_failure_ratio']=s['successes']/s['unsuccessful_episodes'];Path('tools/supervisor_status.json').write_text(json.dumps(s,indent=2));print({k:s[k] for k in ['successes','unsuccessful_episodes','verified_successes_trailing_hour']})
